//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Settings/MobaInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MobaInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MobaInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MobaInputActions"",
    ""maps"": [
        {
            ""name"": ""GameplayMap"",
            ""id"": ""6c89a843-506b-4e9f-9318-7ec0c1fdb8e5"",
            ""actions"": [
                {
                    ""name"": ""SelectMovePosition"",
                    ""type"": ""Button"",
                    ""id"": ""7e412cf8-fa63-40c7-af5a-a7fbddaa8039"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AoeAblility"",
                    ""type"": ""Button"",
                    ""id"": ""34eba5d6-7a82-428e-9bc2-b610923d2085"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillShotAbility"",
                    ""type"": ""Button"",
                    ""id"": ""2cf4bb36-eee2-447b-b759-e79873fc86cd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ConfirmSkillShotAbility"",
                    ""type"": ""Button"",
                    ""id"": ""9235f2aa-029b-46a9-b190-d0af96b298c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8c847192-ea9b-43e8-99be-75c6bfaa11bb"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectMovePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6e5d6b2-6329-4b54-aefd-3b441ce0747a"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AoeAblility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f86d8f72-9204-438f-b3c6-ae3198473eec"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillShotAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b2f62f0-0510-4184-a354-9486f6a68a69"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConfirmSkillShotAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GameplayMap
        m_GameplayMap = asset.FindActionMap("GameplayMap", throwIfNotFound: true);
        m_GameplayMap_SelectMovePosition = m_GameplayMap.FindAction("SelectMovePosition", throwIfNotFound: true);
        m_GameplayMap_AoeAblility = m_GameplayMap.FindAction("AoeAblility", throwIfNotFound: true);
        m_GameplayMap_SkillShotAbility = m_GameplayMap.FindAction("SkillShotAbility", throwIfNotFound: true);
        m_GameplayMap_ConfirmSkillShotAbility = m_GameplayMap.FindAction("ConfirmSkillShotAbility", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GameplayMap
    private readonly InputActionMap m_GameplayMap;
    private List<IGameplayMapActions> m_GameplayMapActionsCallbackInterfaces = new List<IGameplayMapActions>();
    private readonly InputAction m_GameplayMap_SelectMovePosition;
    private readonly InputAction m_GameplayMap_AoeAblility;
    private readonly InputAction m_GameplayMap_SkillShotAbility;
    private readonly InputAction m_GameplayMap_ConfirmSkillShotAbility;
    public struct GameplayMapActions
    {
        private @MobaInputActions m_Wrapper;
        public GameplayMapActions(@MobaInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectMovePosition => m_Wrapper.m_GameplayMap_SelectMovePosition;
        public InputAction @AoeAblility => m_Wrapper.m_GameplayMap_AoeAblility;
        public InputAction @SkillShotAbility => m_Wrapper.m_GameplayMap_SkillShotAbility;
        public InputAction @ConfirmSkillShotAbility => m_Wrapper.m_GameplayMap_ConfirmSkillShotAbility;
        public InputActionMap Get() { return m_Wrapper.m_GameplayMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayMapActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayMapActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayMapActionsCallbackInterfaces.Add(instance);
            @SelectMovePosition.started += instance.OnSelectMovePosition;
            @SelectMovePosition.performed += instance.OnSelectMovePosition;
            @SelectMovePosition.canceled += instance.OnSelectMovePosition;
            @AoeAblility.started += instance.OnAoeAblility;
            @AoeAblility.performed += instance.OnAoeAblility;
            @AoeAblility.canceled += instance.OnAoeAblility;
            @SkillShotAbility.started += instance.OnSkillShotAbility;
            @SkillShotAbility.performed += instance.OnSkillShotAbility;
            @SkillShotAbility.canceled += instance.OnSkillShotAbility;
            @ConfirmSkillShotAbility.started += instance.OnConfirmSkillShotAbility;
            @ConfirmSkillShotAbility.performed += instance.OnConfirmSkillShotAbility;
            @ConfirmSkillShotAbility.canceled += instance.OnConfirmSkillShotAbility;
        }

        private void UnregisterCallbacks(IGameplayMapActions instance)
        {
            @SelectMovePosition.started -= instance.OnSelectMovePosition;
            @SelectMovePosition.performed -= instance.OnSelectMovePosition;
            @SelectMovePosition.canceled -= instance.OnSelectMovePosition;
            @AoeAblility.started -= instance.OnAoeAblility;
            @AoeAblility.performed -= instance.OnAoeAblility;
            @AoeAblility.canceled -= instance.OnAoeAblility;
            @SkillShotAbility.started -= instance.OnSkillShotAbility;
            @SkillShotAbility.performed -= instance.OnSkillShotAbility;
            @SkillShotAbility.canceled -= instance.OnSkillShotAbility;
            @ConfirmSkillShotAbility.started -= instance.OnConfirmSkillShotAbility;
            @ConfirmSkillShotAbility.performed -= instance.OnConfirmSkillShotAbility;
            @ConfirmSkillShotAbility.canceled -= instance.OnConfirmSkillShotAbility;
        }

        public void RemoveCallbacks(IGameplayMapActions instance)
        {
            if (m_Wrapper.m_GameplayMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayMapActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayMapActions @GameplayMap => new GameplayMapActions(this);
    public interface IGameplayMapActions
    {
        void OnSelectMovePosition(InputAction.CallbackContext context);
        void OnAoeAblility(InputAction.CallbackContext context);
        void OnSkillShotAbility(InputAction.CallbackContext context);
        void OnConfirmSkillShotAbility(InputAction.CallbackContext context);
    }
}
